# Generated by Plain 0.165.0 on 2026-09-28 01:25

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("examples", postgres.JSONField(default=[], required=False)),
                ("instructions", postgres.TextField()),
                ("language", postgres.TextField(max_length=32)),
                (
                    "promoted_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                ("scores", postgres.JSONField(default={}, required=False)),
                (
                    "source",
                    postgres.TextField(
                        default="manual", max_length=100, required=False
                    ),
                ),
                (
                    "status",
                    postgres.TextField(
                        choices=[
                            ("draft", "draft"),
                            ("candidate", "candidate"),
                            ("active", "active"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "strategy",
                    postgres.TextField(
                        choices=[("llm", "llm"), ("hybrid", "hybrid")], max_length=16
                    ),
                ),
                ("version", postgres.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "api_base",
                    postgres.TextField(default="", max_length=500, required=False),
                ),
                (
                    "api_key_env",
                    postgres.TextField(default="", max_length=100, required=False),
                ),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("enabled_for_generation", postgres.BooleanField(default=True)),
                ("enabled_for_judging", postgres.BooleanField(default=False)),
                ("litellm_model", postgres.TextField(max_length=200)),
                ("max_input_tokens", postgres.IntegerField(default=128000)),
                ("name", postgres.TextField(max_length=100)),
                ("notes", postgres.TextField(default="", required=False)),
                ("params", postgres.JSONField(default={}, required=False)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuntimeSettings",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("key", postgres.TextField(default="default", max_length=16)),
                (
                    "trace_backends",
                    postgres.JSONField(default=["native"], required=False),
                ),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                (
                    "active_model",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="settings_as_active_model",
                        required=False,
                        to="registry.modelconfig",
                    ),
                ),
                (
                    "default_judge_model",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="settings_as_default_judge",
                        required=False,
                        to="registry.modelconfig",
                    ),
                ),
            ],
        ),
    )
