# Generated by Plain 0.165.0 on 2026-09-28 05:37

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = (("registry", "0002_seed_defaults"),)

    operations = (
        migrations.CreateModel(
            name="PromptPromotion",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                (
                    "kind",
                    postgres.TextField(
                        choices=[("promote", "promote"), ("rollback", "rollback")],
                        default="promote",
                        max_length=16,
                    ),
                ),
                ("language", postgres.TextField(max_length=32)),
                ("note", postgres.TextField(default="", required=False)),
                ("scores", postgres.JSONField(default={}, required=False)),
                ("strategy", postgres.TextField(max_length=16)),
                (
                    "previous",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.RESTRICT,
                        related_query_name="replaced_by",
                        required=False,
                        to="registry.promptversion",
                    ),
                ),
                (
                    "prompt_version",
                    postgres.ForeignKeyField(
                        on_delete=postgres.RESTRICT,
                        related_query_name="promotions",
                        to="registry.promptversion",
                    ),
                ),
            ],
        ),
    )
