# Generated by Plain 0.165.0 on 2026-09-28 03:54

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="GoldSet",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("language", postgres.TextField(max_length=32)),
                ("name", postgres.TextField(max_length=100)),
                ("notes", postgres.TextField(default="", required=False)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expected", postgres.JSONField()),
                ("input", postgres.JSONField()),
                ("notes", postgres.TextField(default="", required=False)),
                ("seed_error", postgres.TextField(default="", required=False)),
                (
                    "seed_status",
                    postgres.TextField(
                        choices=[
                            ("", ""),
                            ("pending", "pending"),
                            ("running", "running"),
                            ("failed", "failed"),
                        ],
                        default="",
                        max_length=16,
                        required=False,
                    ),
                ),
                ("source", postgres.TextField(default="manual", max_length=100)),
                (
                    "split",
                    postgres.TextField(
                        choices=[("train", "train"), ("dev", "dev"), ("test", "test")],
                        default="train",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    postgres.TextField(
                        choices=[("draft", "draft"), ("approved", "approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                (
                    "gold_set",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        related_query_name="examples",
                        to="goldsets.goldset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldExampleRevision",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("change", postgres.TextField(max_length=100)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expected", postgres.JSONField()),
                ("notes", postgres.TextField(default="", required=False)),
                ("split", postgres.TextField(max_length=8)),
                ("status", postgres.TextField(max_length=16)),
                (
                    "example",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="goldsets.goldexample"
                    ),
                ),
            ],
        ),
    )
