#!/bin/sh -e

for app in docs_app tuning_app; do
    if [ ! -f "$app/.env" ]; then
        echo "Copying $app/.env.example to $app/.env"
        cp "$app/.env.example" "$app/.env"
    fi
done

echo "Installing dependencies with uv"
uv sync --all-packages
