# Generated by Plain 0.165.0 on 2026-09-28 02:58

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = (("registry", "0002_seed_defaults"),)

    operations = (
        migrations.CreateModel(
            name="ModelTest",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("error", postgres.TextField(default="", required=False)),
                (
                    "finished_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                (
                    "latency_ms",
                    postgres.IntegerField(
                        allow_null=True, default=None, required=False
                    ),
                ),
                ("litellm_model", postgres.TextField(max_length=200)),
                (
                    "status",
                    postgres.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "llm_model",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        related_query_name="tests",
                        to="registry.modelconfig",
                    ),
                ),
            ],
        ),
    )
