# Generated by Plain 0.165.0 on 2026-09-28 12:34

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = (
        ("evals", "0002_seed_metric_version"),
        ("registry", "0003_promptpromotion"),
        ("goldsets", "0001_initial"),
    )

    operations = (
        migrations.CreateModel(
            name="OptimizationRun",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("error", postgres.TextField(default="", required=False)),
                (
                    "finished_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                (
                    "gold_set_hash",
                    postgres.TextField(default="", max_length=64, required=False),
                ),
                (
                    "judge_name",
                    postgres.TextField(default="", max_length=100, required=False),
                ),
                ("language", postgres.TextField(max_length=32)),
                (
                    "optimizer",
                    postgres.TextField(
                        choices=[
                            ("bootstrap_few_shot", "bootstrap_few_shot"),
                            ("bootstrap_random_search", "bootstrap_random_search"),
                            ("mipro_v2", "mipro_v2"),
                            ("copro", "copro"),
                        ],
                        max_length=32,
                    ),
                ),
                ("params", postgres.JSONField(default={}, required=False)),
                (
                    "stage",
                    postgres.TextField(default="", max_length=16, required=False),
                ),
                ("started_at", postgres.DateTimeField(allow_null=True, required=False)),
                (
                    "status",
                    postgres.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "task_model_name",
                    postgres.TextField(default="", max_length=100, required=False),
                ),
                (
                    "trace_id",
                    postgres.TextField(default="", max_length=32, required=False),
                ),
                ("train_examples", postgres.IntegerField(default=0)),
                ("trial_log", postgres.JSONField(default=[], required=False)),
                (
                    "base_prompt",
                    postgres.ForeignKeyField(
                        on_delete=postgres.RESTRICT,
                        related_query_name="optimization_bases",
                        to="registry.promptversion",
                    ),
                ),
                (
                    "candidate",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="optimization_candidates",
                        required=False,
                        to="registry.promptversion",
                    ),
                ),
                (
                    "eval_run",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="optimization_runs",
                        required=False,
                        to="evals.evalrun",
                    ),
                ),
                (
                    "gold_set",
                    postgres.ForeignKeyField(
                        on_delete=postgres.RESTRICT,
                        related_query_name="optimization_runs",
                        to="goldsets.goldset",
                    ),
                ),
                (
                    "judge_model",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="optimization_runs_judging",
                        required=False,
                        to="registry.modelconfig",
                    ),
                ),
                (
                    "task_model",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="optimization_runs_task",
                        required=False,
                        to="registry.modelconfig",
                    ),
                ),
            ],
        ),
    )
