# Generated by Plain 0.165.0 on 2026-09-27 22:40

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="TraceSpan",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("attributes", postgres.JSONField(default={}, required=False)),
                ("duration_ms", postgres.FloatField()),
                ("end_time", postgres.DateTimeField()),
                ("events", postgres.JSONField(default=[], required=False)),
                (
                    "generation_id",
                    postgres.BigIntegerField(
                        allow_null=True, default=None, required=False
                    ),
                ),
                ("is_llm", postgres.BooleanField(default=False)),
                ("kind", postgres.TextField(max_length=16)),
                ("name", postgres.TextField(max_length=512)),
                (
                    "parent_span_id",
                    postgres.TextField(default="", max_length=16, required=False),
                ),
                ("resource", postgres.JSONField(default={}, required=False)),
                ("span_id", postgres.TextField(max_length=16)),
                ("start_time", postgres.DateTimeField()),
                ("status_code", postgres.TextField(max_length=8)),
                ("status_message", postgres.TextField(default="", required=False)),
                ("trace_id", postgres.TextField(max_length=32)),
            ],
        ),
    )
