# Generated by Plain 0.165.0 on 2026-09-27 23:22

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="Generation",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                (
                    "doc_json",
                    postgres.JSONField(allow_null=True, default=None, required=False),
                ),
                (
                    "error_code",
                    postgres.TextField(default="", max_length=32, required=False),
                ),
                ("error_detail", postgres.JSONField(default={}, required=False)),
                (
                    "finished_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                ("input_blob", postgres.BinaryField()),
                ("input_bytes", postgres.IntegerField()),
                (
                    "input_entry",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
                (
                    "input_filename",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
                ("input_manifest", postgres.JSONField(default={}, required=False)),
                (
                    "input_origin",
                    postgres.TextField(
                        choices=[("paste", "paste"), ("file", "file"), ("zip", "zip")],
                        max_length=8,
                    ),
                ),
                ("input_sha256", postgres.TextField(max_length=64)),
                (
                    "language",
                    postgres.TextField(default="", max_length=32, required=False),
                ),
                (
                    "model",
                    postgres.TextField(default="", max_length=128, required=False),
                ),
                (
                    "program_version",
                    postgres.TextField(default="", max_length=64, required=False),
                ),
                ("progress", postgres.JSONField(default={}, required=False)),
                (
                    "stage",
                    postgres.TextField(default="", max_length=16, required=False),
                ),
                ("started_at", postgres.DateTimeField(allow_null=True, required=False)),
                (
                    "status",
                    postgres.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "trace_id",
                    postgres.TextField(default="", max_length=32, required=False),
                ),
                (
                    "trace_span_id",
                    postgres.TextField(default="", max_length=16, required=False),
                ),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("comment", postgres.TextField(default="", required=False)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                (
                    "operation_id",
                    postgres.TextField(default="", max_length=512, required=False),
                ),
                ("score", postgres.SmallIntegerField()),
                (
                    "trace_id",
                    postgres.TextField(default="", max_length=32, required=False),
                ),
                (
                    "generation",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="generations.generation"
                    ),
                ),
            ],
        ),
    )
