# Generated by Plain 0.165.0 on 2026-09-28 01:25

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = (
        ("registry", "0001_initial"),
        ("generations", "0001_initial"),
    )

    operations = (
        migrations.RemoveField(
            model_name="generation",
            name="program_version",
        ),
        migrations.AddField(
            model_name="generation",
            name="cost_usd",
            field=postgres.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="generation",
            name="input_tokens",
            field=postgres.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generation",
            name="latency_ms",
            field=postgres.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generation",
            name="llm_model",
            field=postgres.ForeignKeyField(
                allow_null=True,
                on_delete=postgres.SET_NULL,
                related_query_name="generations",
                required=False,
                to="registry.modelconfig",
            ),
        ),
        migrations.AddField(
            model_name="generation",
            name="output_tokens",
            field=postgres.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generation",
            name="prompt_label",
            field=postgres.TextField(default="", max_length=200, required=False),
        ),
        migrations.AddField(
            model_name="generation",
            name="prompt_version",
            field=postgres.ForeignKeyField(
                allow_null=True,
                on_delete=postgres.SET_NULL,
                related_query_name="generations",
                required=False,
                to="registry.promptversion",
            ),
        ),
        migrations.AddField(
            model_name="generation",
            name="strategy",
            field=postgres.TextField(
                choices=[("llm", "llm"), ("hybrid", "hybrid"), ("parser", "parser")],
                default="llm",
                max_length=8,
            ),
        ),
    )
